#!/bin/bash
# Fetch secrets from Secret Manager during Docker build
# This script is used when secrets are available as build arguments

set -e

# If build args are provided, export them as environment variables
if [ -n "$MOMENTUM_NEXT_PUBLIC_FIREBASE_API_KEY" ]; then
    export MOMENTUM_NEXT_PUBLIC_FIREBASE_API_KEY
    export NEXT_PUBLIC_FIREBASE_API_KEY=$MOMENTUM_NEXT_PUBLIC_FIREBASE_API_KEY
fi

if [ -n "$MOMENTUM_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN" ]; then
    export MOMENTUM_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    export NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$MOMENTUM_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
fi

if [ -n "$MOMENTUM_NEXT_PUBLIC_FIREBASE_PROJECT_ID" ]; then
    export MOMENTUM_NEXT_PUBLIC_FIREBASE_PROJECT_ID
    export NEXT_PUBLIC_FIREBASE_PROJECT_ID=$MOMENTUM_NEXT_PUBLIC_FIREBASE_PROJECT_ID
fi

if [ -n "$MOMENTUM_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET" ]; then
    export MOMENTUM_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    export NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$MOMENTUM_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
fi

if [ -n "$MOMENTUM_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID" ]; then
    export MOMENTUM_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    export NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$MOMENTUM_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
fi

if [ -n "$MOMENTUM_NEXT_PUBLIC_FIREBASE_APP_ID" ]; then
    export MOMENTUM_NEXT_PUBLIC_FIREBASE_APP_ID
    export NEXT_PUBLIC_FIREBASE_APP_ID=$MOMENTUM_NEXT_PUBLIC_FIREBASE_APP_ID
fi

# Execute the command passed as arguments
exec "$@"

