import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import { GeminiChatbot } from '../gemini-chatbot';
import { GlobalChatbotProvider } from '@/contexts/global-chatbot-context';

// Mock JobQueueProvider to prevent "useJobQueue must be used within a JobQueueProvider" error
vi.mock('@/contexts/job-queue-context', () => ({
  JobQueueProvider: ({ children }: any) => children,
  useJobQueue: () => ({
    state: { jobs: [], isExpanded: false, isPanelVisible: true },
    addJob: vi.fn(() => 'mock-job-id'),
    updateJob: vi.fn(),
    removeJob: vi.fn(),
    clearCompleted: vi.fn(),
    cancelJob: vi.fn(),
    startJob: vi.fn(),
    completeJob: vi.fn(),
    failJob: vi.fn(),
    setProgress: vi.fn(),
    toggleExpanded: vi.fn(),
    setExpanded: vi.fn(),
    setPanelVisible: vi.fn(),
    getActiveJobs: vi.fn(() => []),
    getCompletedJobs: vi.fn(() => []),
    getJobById: vi.fn(),
    hasActiveJobs: vi.fn(() => false),
    isJobStalled: vi.fn(() => false),
    getStalledJobs: vi.fn(() => []),
  }),
  useJob: () => ({
    jobId: null,
    create: vi.fn(() => 'mock-job-id'),
    start: vi.fn(),
    complete: vi.fn(),
    fail: vi.fn(),
    progress: vi.fn(),
    update: vi.fn(),
    getJob: vi.fn(),
  }),
}));

// Mock dependencies
vi.mock('next/navigation', () => ({
  useRouter: () => ({ push: vi.fn() }),
}));

vi.mock('@/hooks/use-toast', () => ({
  useToast: () => ({ toast: vi.fn() }),
}));

// Mock fetch
global.fetch = vi.fn();

// Mock scrollIntoView and scrollTo (JSDOM doesn't implement these)
Element.prototype.scrollIntoView = vi.fn();
Element.prototype.scrollTo = vi.fn();

describe('GeminiChatbot', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should render thinking process from history', async () => {
    // Mock chat history response
    const mockHistory = {
      messages: [
        {
          id: 'msg-1',
          role: 'user',
          content: 'Hello',
          createdAt: new Date().toISOString(),
        },
        {
          id: 'msg-2',
          role: 'assistant',
          content: 'Hello! I am thinking.',
          thoughts: ['Thinking step 1', 'Thinking step 2'],
          createdAt: new Date().toISOString(),
        },
      ],
    };

    (global.fetch as any).mockResolvedValue({
      ok: true,
      json: async () => mockHistory,
    });

    render(
      <GlobalChatbotProvider>
        <GeminiChatbot brandId="test-brand" />
      </GlobalChatbotProvider>
    );

    // Verify thinking process appears
    await waitFor(() => {
      expect(screen.getByText(/Thinking Process/i)).toBeInTheDocument();
    });

    // Verify logs are displayed (might be collapsed but in DOM)
    expect(screen.getByText('Thinking step 1')).toBeInTheDocument();
    expect(screen.getByText('Thinking step 2')).toBeInTheDocument();
  });

  it('should render explainability card from history for agent-generated images', async () => {
    // Mock chat history response with explainability data
    const mockHistory = {
      messages: [
        {
          id: 'msg-1',
          role: 'user',
          content: 'Generate an image of a sunset',
          createdAt: new Date().toISOString(),
        },
        {
          id: 'msg-2',
          role: 'assistant',
          content: 'Here is a beautiful sunset image.',
          media: [{ type: 'image', url: 'https://example.com/sunset.jpg' }],
          explainability: {
            summary: 'Image generated by AI Agent using Imagen 4.0',
            confidence: 0.85,
            appliedControls: ['AI Agent Generation', 'Imagen 4.0'],
            brandElements: ['Warm colors', 'Natural lighting'],
            avoidedElements: ['Dark tones'],
          },
          createdAt: new Date().toISOString(),
        },
      ],
    };

    (global.fetch as any).mockResolvedValue({
      ok: true,
      json: async () => mockHistory,
    });

    render(
      <GlobalChatbotProvider>
        <GeminiChatbot brandId="test-brand" />
      </GlobalChatbotProvider>
    );

    // Verify explainability card appears (the component renders "Team Intelligence Influence" header)
    await waitFor(() => {
      expect(screen.getByText(/Team Intelligence Influence/i)).toBeInTheDocument();
    });

    // Verify summary is displayed
    expect(screen.getByText(/Image generated by AI Agent using Imagen 4.0/i)).toBeInTheDocument();

    // Verify confidence is displayed (85% as integer)
    expect(screen.getByText(/85% confidence/i)).toBeInTheDocument();
  });

  it('should render explainability card from history for agent-generated videos', async () => {
    // Mock chat history response with explainability data for video
    const mockHistory = {
      messages: [
        {
          id: 'msg-1',
          role: 'user',
          content: 'Generate a video of ocean waves',
          createdAt: new Date().toISOString(),
        },
        {
          id: 'msg-2',
          role: 'assistant',
          content: 'Here is a video of ocean waves.',
          media: [{ type: 'video', url: 'https://example.com/waves.mp4' }],
          explainability: {
            summary: 'Video generated by AI Agent using Veo 2',
            confidence: 0.9,
            appliedControls: ['AI Agent Generation', 'Veo 2'],
            brandElements: [],
            avoidedElements: [],
          },
          createdAt: new Date().toISOString(),
        },
      ],
    };

    (global.fetch as any).mockResolvedValue({
      ok: true,
      json: async () => mockHistory,
    });

    render(
      <GlobalChatbotProvider>
        <GeminiChatbot brandId="test-brand" />
      </GlobalChatbotProvider>
    );

    // Verify explainability card appears for video
    await waitFor(() => {
      expect(screen.getByText(/Team Intelligence Influence/i)).toBeInTheDocument();
    });

    // Verify video-specific summary is displayed
    expect(screen.getByText(/Video generated by AI Agent using Veo 2/i)).toBeInTheDocument();

    // Verify confidence is displayed (90% as integer)
    expect(screen.getByText(/90% confidence/i)).toBeInTheDocument();
  });
});
